"""Bind this development package to its source files and protect the baseline.

This is a publication check, not another mechanical or electrical test suite.
CAD evidence is generated by each variant's own build/check command.
"""
from pathlib import Path
import hashlib
import json
import re
import subprocess

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
BASELINE = '4a67463082116249690cc5c4d886d38d5104b3b4'

def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

def git(*args):
    return subprocess.check_output(['git', *args], cwd=ROOT).decode('utf8').strip()

def main():
    checks = []
    def check(name, passed, detail):
        checks.append({'name': name, 'passed': bool(passed), 'detail': detail})
    changes = git('diff', '--name-only', BASELINE, '--', 'output', 'outputs', 'RevE-ENGINEERING')
    check('Rev_I_baseline_unchanged', not changes, changes.splitlines())
    legacy = 'output/release-review/RevE-ENGINEERING'
    original_py = set(git('ls-tree', '--name-only', f'{BASELINE}:{legacy}').splitlines())
    original_py = {s for s in original_py if s.endswith('.py')}
    current_py = {p.name for p in (ROOT / legacy).glob('*.py')}
    check('legacy_source_inventory_unchanged', original_py == current_py,
          {'added': sorted(current_py-original_py), 'missing': sorted(original_py-current_py)})
    reports = [
        HERE/'common/controls/pin-reservation-check.json',
        HERE/'common/location/output/verification.json',
        HERE/'small-atc/output/fit-report.json',
        HERE/'small-atc/output/carrier-route-report.json',
        HERE/'small-atc/output/preview-verification.json',
        HERE/'48x96/layout-verification.json',
        HERE/'48x96/static-verification.json',
        HERE/'48x96/preview-verification.json',
        HERE/'48x96/package-verification.json',
        HERE/'exchange-verification.json',
    ]
    for path in reports:
        if not path.exists():
            check('report_exists', False, str(path.relative_to(ROOT)))
            continue
        data = json.loads(path.read_text(encoding='utf8'))
        if isinstance(data.get('passed'), bool):
            check('reported_bounded_check_passed', data['passed'], str(path.relative_to(ROOT)))
        if 'sources_changed_during_check' in data:
            check('sources_stable_during_check', not data['sources_changed_during_check'], str(path.relative_to(ROOT)))
        found = 0
        for key in ('sources', 'source_sha256', 'source_sha256_before', 'source_sha256_after'):
            mapping = data.get(key)
            if isinstance(mapping, dict):
                for rel, digest in mapping.items():
                    if not isinstance(digest, str) or not re.fullmatch('[0-9a-f]{64}', digest):
                        continue
                    source = ROOT / rel.replace('\\', '/')
                    if not source.is_file():
                        source = path.parent / rel.replace('\\', '/')
                    check('source_hash', source.is_file() and sha(source) == digest,
                          {'report': str(path.relative_to(ROOT)), 'source': rel})
                    found += 1
        if path.parent.name == '48x96' and isinstance(data.get('source_sha256'), str):
            check('source_hash', sha(path.parent/'layout.py') == data['source_sha256'],
                  {'report': str(path.relative_to(ROOT)), 'source': 'variants/48x96/layout.py'})
            found += 1
        check('report_has_source_binding', found > 0, str(path.relative_to(ROOT)))
        for rel, digest in data.get('artifact_sha256', {}).items():
            artifact = ROOT/rel
            if not artifact.is_file():
                artifact = path.parent/rel
            check('rendered_artifact_hash', artifact.is_file() and sha(artifact) == digest,
                  {'report': str(path.relative_to(ROOT)), 'artifact': rel})
        for item in data.get('images', []):
            check('preview_image_hash', sha(ROOT/item['file']) == item['sha256'], item['file'])
        if 'fit_report_sha256' in data:
            check('preview_fit_report_hash', sha(path.parent/'fit-report.json') == data['fit_report_sha256'], str(path.relative_to(ROOT)))
        if path.name == 'exchange-verification.json':
            for item in data['checks']:
                check('exchange_record_passed', item['passed'], item['file'])
                check('exchange_file_hash', sha(HERE/item['file']) == item['step_sha256'], item['file'])
                check('exchange_report_hash', sha(HERE/item['report']) == item['report_sha256'], item['report'])
        if path.name == 'layout-verification.json':
            for state, item in data['states'].items():
                check('layout_step_hash', sha(path.parent/(state+'.step')) == item['step_sha256'], state)
    # Check local links in new authored Markdown. Full supplier documents stay
    # local research, so public links point to the original supplier instead.
    for path in HERE.rglob('*.md'):
        if 'sources' in path.relative_to(HERE).parts:
            continue
        for target in re.findall(r'\]\(([^)]+)\)', path.read_text(encoding='utf8')):
            if target.startswith(('http:', 'https:', '#', 'mailto:', 'codex:')):
                continue
            target = target.split('#')[0].split(' "')[0].strip('<>')
            resolved = (path.parent/target).resolve()
            check('local_document_link', resolved.exists() or resolved == HERE/'package-verification.json',
                  {'document': str(path.relative_to(ROOT)), 'target': target})
    public_paths = sorted(set(git('ls-files', '--cached', '--others', '--exclude-standard', '--', 'variants').splitlines()))
    omitted = {'variants/package-verification.json'}
    manifest = {rel: sha(ROOT/rel) for rel in public_paths if rel not in omitted and (ROOT/rel).is_file()}
    manifest['README.md'] = sha(ROOT/'README.md')
    result = {
        'status': 'PASS' if all(x['passed'] for x in checks) else 'FAIL',
        'scope': 'Current source bindings, protected Rev I baseline, local document links and public file hashes',
        'baseline_commit': BASELINE,
        'physical_release': False,
        'atc_operational': False,
        'full_sheet_fabrication_release': False,
        'checks': checks,
        'public_files_sha256': manifest,
    }
    (HERE/'package-verification.json').write_text(json.dumps(result, indent=2)+'\n', encoding='utf8')
    failures = [x for x in checks if not x['passed']]
    print(json.dumps({'status': result['status'], 'checks': len(checks), 'public_files': len(manifest), 'failures': failures}, indent=2))
    return 0 if not failures else 1

if __name__ == '__main__':
    raise SystemExit(main())
